version: "3.8"
services:
  web:
    image: "registry.gitlab.com/stephen.werdick/auto-water"
    restart: "always"
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    restart: "always"